<a href="https://colab.research.google.com/github/aimlresearcher/Getting-Started-with-Tensorflow-2.0/blob/main/01_TensorsAndVariables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

tf.debugging.set_log_device_placement(True)

In [3]:
tf.executing_eagerly()

True

### Constant tensors

In [4]:
x0 = tf.constant(3)

x0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
print(x0)

tf.Tensor(3, shape=(), dtype=int32)


In [6]:
x0.shape

TensorShape([])

In [7]:
x0.dtype

tf.int32

In [8]:
x0.numpy()

3

In [9]:
result0 = x0 + 5

result0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [10]:
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])

x1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [11]:
result1 = x1 + 5

result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [12]:
result1 = x1 + tf.constant(5.0)

result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [13]:
result1 = tf.add(x1, tf.constant(5.0))

result1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [14]:
x2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])

x2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [15]:
x2 = tf.cast(x2, tf.float32)

x2

Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>